services:
  controle_nutricional:
    build:
      context: ./controle_nutricional
      dockerfile: ./Dockerfile
    container_name: controle_nutricional
    hostname: controle_nutricional
    restart: always
    volumes:
      - ./controle_nutricional:/service
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres-db
    networks:
      rede-nutriplus:
        aliases:
          - controle-nutricional

  tabela_nutricional:
    build:
      context: ./tabela_nutricional
      dockerfile: ./Dockerfile
    container_name: tabela_nutricional
    hostname: tabela_nutricional
    restart: always
    volumes:
      - ./tabela_nutricional:/service
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres-db
    networks:
      rede-nutriplus:
        aliases:
          - tabela-nutricional

  pratica_nutricional:
    build:
      context: ./pratica_nutricional
      dockerfile: ./Dockerfile
    container_name: pratica_nutricional
    hostname: pratica_nutricional
    restart: always
    volumes:
      - ./pratica_nutricional:/service
    ports:
      - "8083:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres-db
    networks:
      rede-nutriplus:
        aliases:
          - pratica-nutricional

  mcp_nutriplus:
    build:
      context: ./mcp_nutriplus
      dockerfile: ./Dockerfile
    container_name: mcp_nutriplus
    hostname: mcp_nutriplus
    restart: always
    volumes:
      - ./mcp_nutriplus:/service
    ports:
      - "8084:8080"
    environment:
      SERVICO_CONTROLE_URL: http://controle-nutricional:8080
      SERVICO_PRATICA_URL: http://pratica-nutricional:8080
      SERVICO_TABELA_URL: http://tabela-nutricional:8080
    depends_on:
      - controle_nutricional
      - tabela_nutricional
      - pratica_nutricional
    networks:
      - rede-nutriplus

  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations.sql:/docker-entrypoint-initdb.d/migrations.sql
    networks:
      - rede-nutriplus

volumes:
  pgdata:

networks:
  rede-nutriplus: