spring:
  application:
    name: mcp_nutriplus_tabela
  ai:
    mcp:
      server:
        name: mcp_nutriplus_tabela
        protocol: STREAMABLE

servico:
  tabela:
    base-url: ${SERVICO_TABELA_URL:http://localhost:8082}

server:
  port: 8080